### PR TITLE
Saved excursions

### PR DESCRIPTION
**Pull request by hrytsenkooo**
> **Methods**

- GET saved excursions. Get list excursions that saved by user
- POST saved excursions/id. Add excursion to saved
- DELETE saved excursions/id. Remove from saved

> **Changes**
With adding and editing excursion requirements changes:

- range for min-max participants 5-30
- range for price 0-1000

With details excursion now we also get Likes and Dislikes

### CODE REVIEW

**Review by zagrebelnio — CHANGES_REQUESTED** [review]
On GET favorite excursions route the date is not the actual date of the excursion
It is always 0001-01-01T00:00:00
Please fix that issue

**Comment by hrytsenkooo** [comment]
thanks for the correction, changed it

**Comment by znak314** [comment]
Why the minimal number of participant is 5?

**Comment by zagrebelnio** [comment]
> Why the minimal number of participant is 5?

Less than 5 people does not cost the time of the tour guide

**Review by zagrebelnio — APPROVED** [review]
Seems to be correct now, thanks for your efforts!

**Pull request merged**
